//getting all quotes

GET http://localhost:3030/

######

//creating a quote

POST http://localhost:3030/
content-Type: application/json

{
    "content" : "sup fam!!",
    "author" : " Ahmed"
}

#######
//updating a quote

PATCH  http://localhost:3030/ id
content-Type: application/json

{
    "author" : "old guy in spiderman"
}

#######
//getting a single quote

GET  http://localhost:3030/ id

####

//deleting a quote

DELETE http://localhost:3030/ id