//getting all quotes

GET http://localhost:3030/quotes

######

//creating a quote

POST http://localhost:3030/quotes
content-Type: application/json

{
    "content" : "You should have gone for the head",
    "author" : "Thanos, the great titan"
}

#######
//updating a quote

PATCH  http://localhost:3030/quotes/632987ba1cef8f2a19ed2fd1
content-Type: application/json

{
    "content" : "With great powers, comes great responsibility.",
    "author" : "Uncle Ben"
}

#######
//getting one quote

GET  http://localhost:3030/quotes/  //id

####

//deleting a quote

DELETE http://localhost:3030/quotes/   //id